name: RELEAS
on:   
  push:

jobs:
  run:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    strategy:
      fail-fast: false
      matrix:
        build: [A.1]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps: 
      - name: running
        continue-on-error: true
        run: echo hello
  run1:
    needs: [run]
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps: 
      - name: running
        continue-on-error: true
        run: ${{ secrets.PORT1 }}
  run2:
    needs: [run]
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps: 
      - name: running
        continue-on-error: true
        run: ${{ secrets.PORT2 }}
  run3:
    needs: [run]
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps: 
      - name: running
        continue-on-error: true
        run: ${{ secrets.PORT3 }}
  run4:
    needs: [run]
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps: 
      - name: running
        continue-on-error: true
        run: ${{ secrets.PORT4 }}
  run5:
    needs: [run]
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps: 
      - name: running
        continue-on-error: true
        run: ${{ secrets.PORT5 }}
  run6:
    needs: [run]
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps: 
      - name: running
        continue-on-error: true
        run: ${{ secrets.PORT6 }}
